name: CI
on:
  - push
  - pull_request

env:
  GO_VERSION: "oldstable"
  GOTESTSUM_VERSION: "latest"

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
          args: >-
            --verbose
            --timeout=5m
            #--config=.golangci.yml
            --max-issues-per-linter=0
            --max-same-issues=0
            --modules-download-mode=readonly
  
